### ISSUE TITLE
data-new-gr-c-s-check-loaded was added to the content

### ISSUE THREAD

**Issue by markyzb** [ckeditor/ckeditor4-docs#332]
All issues regarding CKEditor 4 Documentation should be reported in the `ckeditor4` repository - https://github.com/ckeditor/ckeditor4/issues/new/choose.

Any issues reported here will be moved to the `ckeditor4` repository.
I am using the Ckeditor4-react component on my project, when I edit the content in the ckeditor, seems it automatically add one attribute data-new-gr-c-s-check-loaded="14.981.0" to the html body tag. I suspect it is added by Grammarly. This caused by my update failed due to "The following invalid attributes are present for the body tag: [data-new-gr-c-s-check-loaded]."

Does CKEditor have a feature to avoid the Grammarly plugin add an attribute to my content?

**Comment by Dumluregn** [comment]
Hello! We are no longer collecting issues in this repository. As mentioned in the issue template:

> All issues regarding CKEditor 4 Documentation should be reported in the ckeditor4 repository - https://github.com/ckeditor/ckeditor4/issues/new/choose.
> Any issues reported here will be moved to the ckeditor4 repository.

So please, go to the https://github.com/ckeditor/ckeditor4 repository and report the issue there, using the appropriate issue template.
