### ISSUE TITLE
Getting 404 Error when we copy and paste the image and content from word to editor

### ISSUE THREAD

**Issue by manikavasakam** [ckeditor/ckeditor4-docs#335]
All issues regarding CKEditor 4 Documentation should be reported in the `ckeditor4` repository - https://github.com/ckeditor/ckeditor4/issues/new/choose.

Any issues reported here will be moved to the `ckeditor4` repository.
![image](https://user-images.githubusercontent.com/74532669/99229877-9a699600-2814-11eb-9e26-7ec78532be75.png)

**Comment by manikavasakam** [comment]
the above issue happened in ckeditor 4

**Comment by manikavasakam** [comment]
Can you please help me sir/madam.

**Comment by Dumluregn** [comment]
Hello, the issue tracker for CKEditor 4 is [here](https://github.com/ckeditor/ckeditor4/issues). When reporting an issue, please remember to follow the provided template.
